version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always
  backend:
    image: isoley/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static/
      - media:/app/media/
  frontend:
    image: isoley/foodgram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static/
  gateway:
    image: isoley/foodgram_gateway:latest
    env_file: .env
    depends_on:
      - backend
    volumes:
      - static:/staticfiles/
      - media:/media/
    ports:
      - 8000:80
    restart: always
